version: "3.1"
services:
  local-sqs:
    image: localstack/localstack:0.10.4
    container_name: sqs-local
    ports:
      - 4576:4576
    environment:
      SERVICES: sqs
      DEFAULT_REGION: ap-southeast-2
      AWS_REGION: ap-southeast-2
      AWS_ACCESS_KEY_ID: x
      AWS_SECRET_KEY: x
      LAMBDA_REMOTE_DOCKER: 0
